<?xml version="1.0" encoding="utf-8"?><Database Name="EmpDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EmpSalary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>